### ISSUE TITLE
[DevOps] Add CodeClimate style fomatter to use apigee-lint into GitLab CI/CD

### ISSUE THREAD

**Issue by ipierre1** [apigee/apigeelint#427]
To use full functionnalities on GitLab CI/CD, it would be nice to implement codeclimate formatter to use codequality reports artifact into pipeline job artifacts as bellow: 

```yml
apigeelint:
  stage: lint
  image: node:12-alpine
  before_script:
    - npm install -g apigeelint
  script:
    - apigeelint -f codeclimate.js > apigeelint-results.json
  artifacts:
    reports:
      codequality:
        - "${CI_PROJECT_DIR}/apigeelint-results.json"
```

Code Quality of GitLab use CodeClimate json format, with enforcement on fingerprint which is not optional for GitLab CI/CD.

Codequality : https://docs.gitlab.com/ee/ci/testing/code_quality.html
Codeclimate specification : https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types
